name: Docker Image CI

env:
  GIT_REF: ${{ github.ref }}
  GIT_SHA: ${{ github.sha }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & push the Docker image
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker build . --file Dockerfile --tag joemsak/joesak.com:$GIT_SHA
        docker push joemsak/joesak.com:$GIT_SHA

    - uses: actions/checkout@v2
    - name: Update cluster
      run: |
        mkdir ~/.kube/
        echo $KUBE_CONFIG > ~/.kube/config
        kubectl apply -k .kubernetes
